### ISSUE TITLE
bug: Plugin: wasi_nn-ggml-cuda not supported in Centos

### ISSUE THREAD

**Issue by oudi** [LlamaEdge/LlamaEdge#152]
### Summary

After run run-llm.sh in centos 7, the errors show below

```
INFO    - WasmEdge Successfully installed
INFO    - Downloading Plugin: wasi_nn-ggml-cuda
ERROR   - Download error from urllib: HTTP Error 404: Not Found
ERROR   - URL: https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasi_nn-ggml-cuda-0.13.5-manylinux2014_x86_64.tar.gz
```

It seems `WasmEdge-plugin-wasi_nn-ggml-cuda-0.13.5-manylinux2014_x86_64.tar.gz` is not list in the release file, I found It list Ubuntu20.04 in the releases with cuda https://github.com/WasmEdge/WasmEdge/releases/tag/0.13.5 . so does it support other Linux os like centos or debain?

### Reproduction steps

run run-llm.sh in centos 7

### Screenshots

![20240424095804](https://github.com/LlamaEdge/LlamaEdge/assets/2518192/7eb9bb4d-2913-4cea-b88e-2afd3b8bd489)

### Model Information

llama-3-8b-instruct

### Operating system information

Centos 7.6

### ARCH

amd64

### CPU Information

Intel I7

### Memory Size

32GB

### GPU Information

NVIDIA 4090

### VRAM Size

24G

**Comment by hydai** [comment]
The Ubuntu assets can support any distro whose glibc version is the same as or newer than Ubuntu 20.04(glibc 2.31), such as Debian, Fedora, Arch Linux, Almalinux, and more non-legacy Linux.

Since CentOS 7 will be EOL in two months, we don't plan to prepare the pre-built assets for this platform. Instead, our focus is on creating the new release assets for manylinux2_28(glibc 2.28, Almalinux 8, CentOS 8). You can build from source to support such legacy OS.

**Comment by oudi** [comment]
OK, thanks
