### ISSUE TITLE
question: How can I use other models in llamaedge?

### ISSUE THREAD

**Issue by aeroaks** [LlamaEdge/LlamaEdge#167]
### Summary

I see that the models are downloaded from "https://huggingface.co/second-state". Is it possible for me to modify run-llm.sh script and run another model? 

PS: I am trying to run '[starcoder2-7b-Q5_K_M.gguf](https://huggingface.co/second-state/StarCoder2-7B-GGUF/blob/main/starcoder2-7b-Q5_K_M.gguf)' As it is recommended in the list.

**Comment by hydai** [comment]
Yes. If the model is in the gguf format, it should be supported. If not, please raise an issue.

**Comment by aeroaks** [comment]
I was trying the StarCoder2 series of models. I see in the description that there is no "Prompt Type" for them.

**Comment by aeroaks** [comment]
Also, trying to run a listed models in the bash script, I am getting this output

```
repos/llamaedge took 2m57s
❯ bash run-llm.sh --model llama-3-8b-instruct

[+] Using cached model Meta-Llama-3-8B-Instruct-Q5_K_M.gguf

repos/llamaedge
❯ ls -alh | grep Meta-Llama-3-8B-Instruct-Q5_K_M.gguf
-rwxrwxrwx 1 User User 5.4G May 23 16:14 Meta-Llama-3-8B-Instruct-Q5_K_M.gguf
```

**Comment by juntao** [comment]
You can use the `--interactive` flag to confirm all steps.

https://llamaedge.com/docs/user-guide/quick-start-command#interactively-choose-and-confirm-all-steps

But, the `run-llm` script is designed to get started quickly. In order to make full use of the tools, I would suggest to go through the entire process by hand. It only takes 10 minutes most:

https://llamaedge.com/docs/user-guide/get-started-with-llamaedge

**Comment by alabulei1** [comment]
Hi @aeroaks,

Just want to follow up if your question is solved.
